basetenlabs/truss-examples

llama-2-13b-chat/README.md
llama-2-13b-chat/config.yaml
llama-2-13b-chat/examples.yaml
llama-2-13b-chat/model/model.py
llama-2-13b-truss/README.md
llama-2-13b-truss/examples.yaml
llama-2-70b-chat/README.md
llama-2-70b-chat/config.yaml
llama-2-70b-chat/examples.yaml
llama-2-70b-chat/model/model.py
llama-2-70b-truss/README.md
llama-2-70b-truss/examples.yaml
llama-2-7b-chat/README.md
llama-2-7b-chat/config.yaml
llama-2-7b-chat/examples.yaml
llama-2-7b-chat/model/model.py
llama-2-7b-truss/README.md
llama-2-7b-truss/config.yaml
llama-2-7b-truss/examples.yaml
llama-2-7b-truss/model/model.py

This PR:
1. Updates the 7B models to run in `float16` on an A10G like the rest of our 7B parameter LLMs rather than on an A100.
2. Standardizes on `hf_access_token` for consistency with our docs and product, as well as HuggingFace's naming.
3. Updates the READMEs of the 6 Llama 2 models to have corrected and clarified deployment instructions.
4. Updates the READMEs of the 6 Llama 2 models to use the same punctuation and capitalization as Meta uses.
5. Removes unneeded `examples.yaml` files

fixes to Llama 2 READMEs and models

---

llama-2-13b-chat/README.md
llama-2-13b-truss/README.md
llama-2-70b-chat/README.md
llama-2-70b-truss/README.md
llama-2-7b-chat/README.md
llama-2-7b-truss/README.md

Add `max_new_tokens` to example in response to user feedback. I had to use this parameter for Chainlit and LangChain to work properly as I was using longer prompts.

add max new tokens

---

mistral/mistral-7b-instruct-vllm/config.yaml
mistral/mistral-7b-instruct/config.yaml
mistral/mistral-7b/config.yaml

The Mistral 7B model doesn't run on our smallest A10G instance since there isn't enough memory available. This PR updates the `config.yml` to the next largest instance.

Update Memory Requirements for Mistral

---

ci.yaml
mistral/mistral-7b-instruct/model/model.py
mistral/mistral-7b/config.yaml
mistral/mistral-7b/model/model.py

I've discovered that mistral-7B model doesn't work currently due to typo and using model class instead of tokenizer in `model.py`.
I've fixed this, as well as enabled two mistral models on ci tests to catch this error next time.

Fix mistral-7B models in examples

---

.github/workflows/test-examples.yml

Hardcode the python version. Python 3.12 released, and this used that, but truss currently does not support python 3.12.

Run CI on python 3.11.4.

---

deepspeed-mii/README.md
deepspeed-mii/config.yaml
deepspeed-mii/model/model.py

This adds Llama2 7B chat model served with [Microsoft's DeepSpeed MII](https://github.com/microsoft/DeepSpeed-MII) framework.

Add truss example for DeepSpeed MII with Llama2 7B chat model 

---

deepspeed-mii/config.yaml
deepspeed-mii/model/model.py

I've added couple of improvements to DeepSpeed MII:
- Support streaming output
- Do not base it on custom image since newer image was released so it's not needed
- Ignore `mii.serve` exceptions in draft mode to improve dev workflow

Support streaming in DeepSpeed MII truss 

---

deepspeed-mii/config.yaml
deepspeed-mii/model/model.py
llama/llama-2-7b-trt-llm/model/model.py

In order to make benchmarks more apples-to-apples it would be useful to have an ability to keep generating output even if `eos` token was emitted. I've added support for that to deep speed and trt-llm backends.

Add `ignore_eos` support to deep-speed and trt-llm backends

---

mistral/mistral-7b-instruct-vllm/config.yaml
mistral/mistral-7b-instruct-vllm/model/model.py

In order to enable customization of max length supported by engine we need to be able to pass arbitrary config params to vllm engine. Currently we support only passing `repo_id`, I've changed it to `engine_args` with `model` being repo (since that's how vllm engine arg is called).

Add ability to specify engine args to mistral vllm implementation

---

llama/llama-2-7b-trt-llm/README.md
llama/llama-2-7b-trt-llm/config.yaml
mistral/mistral-7b-trt-llm/README.md
mistral/mistral-7b-trt-llm/config.yaml

- Adds model server build config to prevent development deployment of TRT-LLM servers, while we work on adding patching support to these examples

Add model server build config  

---

llama/llama-2-7b-trt-llm/config.yaml
mistral/mistral-7b-trt-llm/config.yaml

This reverts commit 5f5fcb52613ce0cd47d68669028aa211db348781. We should wait for https://github.com/basetenlabs/truss/pull/748 to be released to properly handle this config

Revert "Add model server build config   (#78)"

---

mistral/mistral-7b-chat/config.yaml
mistral/mistral-7b-chat/model/model.py
zephyr/zephyr-7b-alpha/config.yaml
zephyr/zephyr-7b-alpha/model/model.py

There was an issue with using zephyr & mistral with the openai clients where they were returning the full conversation. Fix that, along with another issue in which for zephyr, "null" value for max_tokens was resulting in no content being returned.
Tested both of these agains the OpenAI clients.
```
$ poetry run python test.py
ChatCompletion(id='chatcmpl-91d33382-80ae-4948-90eb-9a5d12bf98d3', choices=[Choice(finish_reason=None, index=0, message=ChatCompletionMessage(content='The 2020 World Series was played at Globe Life Field in Arlington, Texas.', role='assistant', function_call=None, tool_calls=None))], created=1700610404, model='8w672xyq', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=0, prompt_tokens=0, total_tokens=0))
```
```
$ poetry run …
```

Dont return full output

---

llama/llama-2-7b-trt-llm/TRT-LLM-README.md
llama/llama-2-7b-trt-llm/packages/inflight_batcher_llm/tensorrt_llm/config.pbtxt
mistral/mistral-7b-instruct-chat-trt-llm/TRT-LLM-README.md
mistral/mistral-7b-instruct-chat-trt-llm/packages/inflight_batcher_llm/tensorrt_llm/config.pbtxt
mistral/mistral-7b-trt-llm-build-engine/TRT-LLM-README.md
mistral/mistral-7b-trt-llm-build-engine/packages/inflight_batcher_llm/tensorrt_llm/config.pbtxt
templates/trt-llm/TRT-LLM-README.md
templates/trt-llm/packages/inflight_batcher_llm/tensorrt_llm/config.pbtxt

- We found in our benchmarking runs that setting this server config to `False` results in better throughput and latency for the majority of customer use cases we are trying to support, this PR makes the change to the templates these examples are generated from

Set `enable_trt_overlap` to False

---

mistral/mistral-7b-trt-llm-build-engine/config.yaml
templates/generate.yaml

It would be better to use simpler configuration for mistral trt with build engine config.

Use tensor and pipeline parallelism equal to 1 in build engine truss

---

bin/test_example.py
ci.yaml
whisper/faster-whisper-truss/config.yaml

Makes the following changes:
* Remove deepspeed-mii from the CI (it needs an A100, which we just don't have here)
* Fix the faster-whisper truss (I tried pushing it myself, and it worked)
* Add exponential backoff around `truss.push`

Fix examples CI

---

llama/llama-2-7b-trt-llm/model/model.py
mistral/mistral-7b-instruct-chat-trt-llm/model/model.py
templates/trt-llm/model/model.py

The id is 32 bit random which is not good in general, but should unblock benchmarking with multiple workers. I had difficulties passing longer ids to trtllm, so that needs some work. Perhaps we can combine worker id with auto-increment id, will explore  in follow up.

Use randomly generated uuid

---

mistral/mistral-7b-trt-llm-build-engine/README.md
mistral/mistral-7b-trt-llm-build-engine/config.yaml
mistral/mistral-7b-trt-llm-build-engine/model/model.py
templates/generate.yaml

Instruct model is much easier / better to interact with, and supports chat inputs. I've changed out `mistral-7B-trt-llm` model to use Mistral 7B instruct v0.2.

Make mistral trt llm engine build model to use mistral instruct model

---

llama/llama-2-7b-trt-llm/model/model.py
mistral/mistral-7b-instruct-chat-trt-llm-smooth-quant/model/model.py
mistral/mistral-7b-instruct-chat-trt-llm-weights-only-quant/model/model.py
mistral/mistral-7b-instruct-chat-trt-llm/model/model.py
mistral/mistral-7b-trt-llm-build-engine/model/model.py
mistral/mixtral-8x7b-instruct-trt-llm-weights-only-quant/model/model.py
mistral/mixtral-8x7b-instruct-trt-llm/model/model.py
templates/trt-llm/model/model.py

In cases when we run TRT-LLM trusses with more than one worker we download engine files each time worker runs. I've added safeguard on this so we download files only once.

Avoid downloading engine more than once

---

llama/llama-2-7b-trt-llm/packages/inflight_batcher_llm/preprocessing/1/model.py
mistral/mistral-7b-instruct-chat-trt-llm-smooth-quant/packages/inflight_batcher_llm/preprocessing/1/model.py
mistral/mistral-7b-instruct-chat-trt-llm-weights-only-quant/packages/inflight_batcher_llm/preprocessing/1/model.py
mistral/mistral-7b-instruct-chat-trt-llm/packages/inflight_batcher_llm/preprocessing/1/model.py
mistral/mistral-7b-trt-llm-build-engine/packages/inflight_batcher_llm/preprocessing/1/model.py
mistral/mixtral-8x7b-instruct-trt-llm-weights-only-quant/packages/inflight_batcher_llm/preprocessing/1/model.py
mistral/mixtral-8x7b-instruct-trt-llm/packages/inflight_batcher_llm/preprocessing/1/model.py
templates/trt-llm/packages/inflight_batcher_llm/preprocessing/1/model.py

I used logic from https://github.com/triton-inference-server/tensorrtllm_backend/blob/6e6e34e0944c10a82ad0bd526087d72ce16b8d56/all_models/inflight_batcher_llm/preprocessing/1/model.py to pad inputs with `numpy` instead of using `pytorch` which is heavy dependency we don't really need.

Do not use pytorch in trt llm trusses

---

alpaca-7b/README.md
deepfloyd-xl/README.md
flan-t5-xl/README.md
gfp-gan/README.md
gpt-j/README.md
llama/llama-2-7b-trt-llm/README.md
llama/llama-7b/README.md
mistral/mistral-7b-instruct-chat-trt-llm-smooth-quant/README.md
mistral/mistral-7b-instruct-chat-trt-llm-weights-only-quant/README.md
mistral/mistral-7b-instruct-chat-trt-llm/README.md
mistral/mistral-7b-trt-llm-build-engine/README.md
nsql/README.md
stable-diffusion/stable-diffusion/README.md
stablelm/README.md
whisper/whisper-truss/README.md

This PR removes all the `Deploy` buttons from model READMEs. These will likely return in some form after we transition to the new model library but until then lets remove them so the links aren't broken for each of these models.

Remove all deploy buttons

---

llama/llama-2-13b-chat/config.yaml
llama/llama-2-13b/config.yaml
llama/llama-2-70b-chat/config.yaml
llama/llama-2-70b/config.yaml
llama/llama-2-7b-chat-tgi/config.yaml
llama/llama-2-7b-chat/config.yaml
llama/llama-2-7b-trt-llm/config.yaml
llama/llama-2-7b/config.yaml
templates/generate.yaml

In https://github.com/basetenlabs/baseten/pull/7807 & some previous PRs, we added some validation logic to check on baseten when deploying a model whether the user has access to the repo in question or not (with their access token). In order to do this check, we need to have the repo_id that the model is pointing to in Huggingface in the config (it has to be in some sort of structured data to read it).
In this PR, we add the correct repo_id to each of the  llama repos so we can validate them.
A good follow-up to this would be reading the config value in the model.py files instead of hard-coding them there.

Add repo_id to llama repos

---

llama/llama-7b/model/model.py

The previous Huggingface repository no longer existed which caused deployment errors.

Updating Llama 7B tokenizer

---

stable-diffusion/stable-diffusion-xl-1.0-trt/config.yaml

- This change introduces the caching of engine plan files to improve cold starts for this model

add model cache to sdxl trt example

---

stable-diffusion/stable-diffusion-xl-1.0-trt/model/model.py
stable-diffusion/stable-diffusion-xl-1.0-trt/packages/diffusion/trtclip.py
stable-diffusion/stable-diffusion-xl-1.0-trt/packages/diffusion/trtunet.py

Clip trt engines have three bindings, "input_ids", "text_embeddings" and "hidden_states". These are mapped to the form that diffusers pipeline expects; the clip trt engines are thus adapted to replace diffuser counterparts in the base and refiner pipelines.
This should restore the 300ms we were missing compared to https://huggingface.co/stabilityai/stable-diffusion-xl-1.0-tensorrt

Use trt engines for clip and clip2 for TensorRT SDXL

---

templates/trt-llm/packages/client.py

This PR fixes a bug where the `TritonClient` didn't unpack the response from the `TritonServer` to check for errors.

Handling error responses in Triton

---

stable-diffusion/stable-diffusion-xl-1.0-trt/config.yaml

This PR adds the VAE, base model, and refiner to the model cache for faster startup (~45 seconds)

Extend model cache for faster cold starts

---

jina-embeddings/jina-embeddings-v2-base-en/config.yaml

Jina embeddings (https://huggingface.co/jinaai/jina-embeddings-v2-base-en) now requires that users have a huggingface token. After this change & redeploying the model library model, it will be clearer to users that they need to accept terms. 
Note that this won't fix the broken CI, we'll need a huggingface service account that accepts the terms.

Jina embeddings now requires accepting huggingface terms.

---

jina-embeddings/jina-embeddings-v2-base-en/config.yaml
jina-embeddings/jina-embeddings-v2-base-en/model/model.py

Follow-up from https://github.com/basetenlabs/truss-examples/pull/179, actually make use of the secret.
There's a bug in the latest version transformers where the `token` parameter is not respected, which is why I had to do the weird environment variable thing.
Tested by doing `truss push --trusted` in the repo, and ensuring that it deploys on my account.

Actually use secret in jina embeddings

---

gfp-gan/config.yaml

While i was testing an unrelated change (truss types), the gfp-gan truss started failing in CI examples. After retrying a few times, it looked it like it was an issue with the latest version of torchvision (https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13985).
Because we were not pinning torchvision, we were getting this later version, that does not seem to be compatible with gfp-gan.
The quick fix here is pinning torchvision, although I will acknowledge that this is not sustainable, at some point we will need to update gfp-gan library. This at least gets us back to passing CI.
Tested by deploying gfp-gan on staging, it worked successfully.

Pin torchvision for gfp-gan

---

nomic/nomic-embed-v1_5/config.yaml

Messed up the new data model — turns out old image URLs still needed.

fix metadata

---

02-llm/model/model.py

There appears to be a typo when setting the parameters for Mistral inference. top_k is being set using the top_p entry in the request dict

Update typo in model.py "top_p" -> "top_k"

---

mistral/mistral-7b-chat/config.yaml
mistral/mistral-7b-instruct/config.yaml

See https://basetenlabs.slack.com/archives/C052AKXNGES/p1713559863206319 for context, but right now our mistral models in the library will fail unless they have an hf access token.
These are the two that need the hf access token added.
This will change the model library to prompt users to have an hf access token added.

Fix mistral models to have an hf_access_token.

---

mistral/mistral-7b-chat/model/model.py
mistral/mistral-7b-instruct/model/model.py

Follow-up from: https://github.com/basetenlabs/truss-examples/pull/275, actually needed to change the model code also.
Deployed on my local account after accepting the terms for these mistral models.

Actually use the auth tokens when pulling hf repos

---

mistral/mistral-7b-chat/config.yaml
mistral/mistral-7b-instruct-chat-trt-llm/config.yaml
mistral/mistral-7b-instruct/config.yaml

After mistral started requiring accepting terms, we need to start including the hf_access_token in secrets.
Note that for the TRT model, the code already sets the hf_access_token if it's in the secrets (it was generated from some template).
Note that I also added a "model_metadata.repo_id" field to the mistral-7b-chat and instruct models as well so that the terms and conditions link shows up properly.
Deployed the model on my account:
```
$ truss push --publish --wait --remote baseten --trusted
```

Fix mistral trt example.

---

llama/llama-3-70b-instruct/config.yaml

Llama 3 70B only needs 2, not 4, 80 GB GPUs to run inference. I've changed the config and tested the updated config in production.

reduce Llama 3 70B from 4 to 2 H100s

---

02-llm/config.yaml
02-llm/model/model.py
mistral/mistral-7b/config.yaml
mistral/mistral-7b/model/model.py

Fix these to get the CI examples unblocked. For the 02-llm example, this is not ideal anymore, but we can fix the docs later. I still think mistral or llama would be the best examples to use there, even though they both require hf access token now.

Fix truss ci examples

---

alpaca-7b/config.yaml
code-llama-7b-instruct/config.yaml
llama/llama-2-13b-chat/config.yaml
llama/llama-2-70b-chat/config.yaml
llama/llama-2-7b-chat/config.yaml
llama/llama-7b/config.yaml
stablelm/config.yaml

We incremented the minimum python version for truss to 3.9. A bunch of our examples were still using py38.
I deployed the llama-2-7b-chat model successfully.
Redeploy the model library model

Update truss examples to not use py38.

---

lora/config.yaml

This system packages is needed by the control server in Baseten development model.

Make LoRA truss work in baseten development mode

---

whisper/whisper-v3-truss-base64/README.md
whisper/whisper-v3-truss-base64/config.yaml
whisper/whisper-v3-truss-base64/model/model.py

Modified whisper v3 to take base64 as input.
Deployed model, and tested with this script:
```
import requests
import base64
audio_base64 = base64.b64encode(open("Gettysburg.mp3", "rb").read()).decode('utf-8')
resp = requests.post(
"https://model-{MODEL_ID}.api.baseten.co/development/predict",
headers={"Authorization": "Api-Key $BASETEN_API_KEY"},
json={'audio': audio_base64},
)
print(resp.content)
```

Added whisper model that takes base64 input.

---

02-llm/config.yaml
mistral/mistral-7b-chat/config.yaml
mistral/mistral-7b-instruct/config.yaml

Fix Mistral truss-examples, see [issue](https://github.com/huggingface/transformers/issues/31789) for context. Something changed w tokenizers library that we need to update these.
This is the exception that we're seeing:
```
Exception while loading model
Traceback (most recent call last):
File "/app/model_wrapper.py", line 118, in load
self.try_load()
File "/app/model_wrapper.py", line 179, in try_load
retry(
File "/app/common/retry.py", line 20, in retry
raise exc
File "/app/common/retry.py", line 15, in retry
fn()
File "/app/model/model.py", line 34, in load
self.tokenizer = AutoTokenizer.from_pretrained(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/transformers/models/auto/tokenization_auto.py", line 751, in from_pretrained
return …
```

Update transformers on mistral to fix mistral examples

---

mistral/mistral-7b-instruct-chat-trt-llm-h100/config.yaml
mistral/mistral-7b-instruct-chat-trt-llm-smooth-quant/config.yaml
mistral/mistral-7b-instruct-chat-trt-llm-weights-only-quant-h100/config.yaml
mistral/mistral-7b-instruct-chat-trt-llm-weights-only-quant/config.yaml
mistral/mistral-7b-instruct-chat-trt-llm/config.yaml
mistral/mistral-7b-trt-llm-build-engine/config.yaml
mistral/mixtral-8x22b-trt-int8-weights-only/config.yaml
mistral/mixtral-8x22b/config.yaml
mistral/mixtral-8x7b-instruct-trt-llm-h100/config.yaml
mistral/mixtral-8x7b-instruct-trt-llm-weights-only-quant-h100/config.yaml
mistral/mixtral-8x7b-instruct-trt-llm-weights-only-quant/config.yaml
mistral/mixtral-8x7b-instruct-trt-llm/config.yaml

There was a recent change to the Mistral repo on huggingface where they started using a newer transformer feature: This resulted in this: https://github.com/huggingface/transformers/issues/31789.
Bumping the transformers to fix this across all of our mistral models. As a follow-up, we should start pinning the HF repository for all of our examples to prevent this from happening.
I have  tested a couple of the TRT examples, but not _everything_

Bump transformers version for mistrals.

---

mistral/mistral-7b/config.yaml

Missed this one example when make this change: https://github.com/basetenlabs/truss-examples/pull/321

Update transformers version on mistral-7b example

---

phi/phi-3.5-mini/config.yaml
phi/phi-3.5-mini/model/model.py
vllm/model/model.py

Currently when we process `model_input`, we popped the "stream" property. 
We want to maintain this property when openAI compatible mode is enabled so stream works with openAI SDK calls

Fixed stream=True option for VLLM template

---

bin/test_example.py

Improves the truss examples to do the following:
* Fail immediately if there are problems (instead of having to wait 20 minutes)
* Doesn't have a 20 minute timeout if the model is still building
Ran https://github.com/basetenlabs/truss-examples/actions/runs/11633933987/job/32400112601

Improve truss examples CI script

---

poetry.lock
pyproject.toml

Aiming to match the Python version requirements in the [truss repo](https://github.com/basetenlabs/truss/blob/main/pyproject.toml#L54-L55).
Ran `poetry lock` after this change.
I could not change the Python version requirement to be exactly like `truss`' (as in make the lowest supported version 3.8) because ipython 8.14.0 requires at least Python 3.9. Not touching this for now, but `truss` uses `ipython = "^7.16"` ([code](https://github.com/basetenlabs/truss/blob/main/pyproject.toml#L94)) if we want to match exactly.
```
The current project's supported Python range (>=3.8,<3.13) is not compatible with some of the required packages Python requirement:
- ipython requires Python >=3.10, so it will not be satisfied for Python >=3.8,<3.10
- ipython requires Python >=3.10, so it will not be …
```

Modify required python version

---

qwen/engine-qwen-2-5-14b-coder-instruct/README.md
qwen/engine-qwen-2-5-14b-coder-instruct/config.yaml
qwen/engine-qwen-2-5-14b-instruct/README.md
qwen/engine-qwen-2-5-14b-instruct/config.yaml
qwen/engine-qwen-2-5-32b-coder-instruct/README.md
qwen/engine-qwen-2-5-32b-coder-instruct/config.yaml
qwen/engine-qwen-2-5-32b-instruct/README.md
qwen/engine-qwen-2-5-32b-instruct/config.yaml
qwen/engine-qwen-2-5-3b-instruct/README.md
qwen/engine-qwen-2-5-3b-instruct/config.yaml
qwen/engine-qwen-2-5-72b-instruct/README.md
qwen/engine-qwen-2-5-72b-instruct/config.yaml
qwen/engine-qwen-2-5-72b-math-instruct/README.md
qwen/engine-qwen-2-5-72b-math-instruct/config.yaml
qwen/engine-qwen-2-5-7b-coder-instruct/README.md
qwen/engine-qwen-2-5-7b-coder-instruct/config.yaml
qwen/engine-qwen-2-5-7b-instruct/README.md
qwen/engine-qwen-2-5-7b-instruct/config.yaml
qwen/engine-qwen-2-5-7b-math-instruct/README.md
qwen/engine-qwen-2-5-7b-math-instruct/config.yaml

Using the latest edition of the engine builder, this PR adds all 8 qwen 2.5 sizes/variants that we want to use in the model library.
I have manually deployed and tested all 8 of these models to ensure they are working correctly.

Add 8 Qwen models to the model library

---

11-embeddings-reranker-classification-tensorrt/BEI-baai-bge-en-icl-embedding/README.md
11-embeddings-reranker-classification-tensorrt/BEI-baai-bge-en-icl-embedding/config.yaml
11-embeddings-reranker-classification-tensorrt/BEI-baai-bge-large-en-v1.5-embedding/README.md
11-embeddings-reranker-classification-tensorrt/BEI-baai-bge-large-en-v1.5-embedding/config.yaml
11-embeddings-reranker-classification-tensorrt/BEI-baai-bge-multilingual-gemma2-multilingual-embedding/README.md
11-embeddings-reranker-classification-tensorrt/BEI-baai-bge-multilingual-gemma2-multilingual-embedding/config.yaml
11-embeddings-reranker-classification-tensorrt/BEI-baai-bge-reranker-large/README.md
11-embeddings-reranker-classification-tensorrt/BEI-baai-bge-reranker-large/config.yaml
11-embeddings-reranker-classification-tensorrt/BEI-cross-encoder-ms-marco-minilm-l-6-v2-reranker/README.md
11-embeddings-reranker-classification-tensorrt/BEI-cross-encoder-ms-marco-minilm-l-6-v2-reranker/config.yaml
11-embeddings-reranker-classification-tensorrt/BEI-intfloat-e5-mistral-7b-instruct-embedding/README.md
11-embeddings-reranker-classification-tensorrt/BEI-intfloat-e5-mistral-7b-instruct-embedding/config.yaml
11-embeddings-reranker-classification-tensorrt/BEI-intfloat-multilingual-e5-large-instruct-embedding/README.md
11-embeddings-reranker-classification-tensorrt/BEI-intfloat-multilingual-e5-large-instruct-embedding/config.yaml
11-embeddings-reranker-classification-tensorrt/BEI-linq-ai-research-linq-embed-mistral/README.md
11-embeddings-reranker-classification-tensorrt/BEI-linq-ai-research-linq-embed-mistral/config.yaml
11-embeddings-reranker-classification-tensorrt/BEI-prosusai-finbert-classification/README.md
11-embeddings-reranker-classification-tensorrt/BEI-prosusai-finbert-classification/config.yaml
11-embeddings-reranker-classification-tensorrt/BEI-salesforce-sfr-embedding-mistral/README.md
11-embeddings-reranker-classification-tensorrt/BEI-salesforce-sfr-embedding-mistral/config.yaml
11-embeddings-reranker-classification-tensorrt/BEI-samlowe-roberta-base-go_emotions-classification/README.md
11-embeddings-reranker-classification-tensorrt/BEI-samlowe-roberta-base-go_emotions-classification/config.yaml
11-embeddings-reranker-classification-tensorrt/BEI-skywork-skywork-reward-llama-3.1-8b-v0.2-reward-model/README.md
11-embeddings-reranker-classification-tensorrt/BEI-skywork-skywork-reward-llama-3.1-8b-v0.2-reward-model/config.yaml
11-embeddings-reranker-classification-tensorrt/BEI-snowflake-snowflake-arctic-embed-l-v2.0/README.md
11-embeddings-reranker-classification-tensorrt/BEI-snowflake-snowflake-arctic-embed-l-v2.0/config.yaml
11-embeddings-reranker-classification-tensorrt/BEI-whereisai-uae-large-v1-embedding/README.md
11-embeddings-reranker-classification-tensorrt/BEI-whereisai-uae-large-v1-embedding/config.yaml
11-embeddings-reranker-classification-tensorrt/README.md
11-embeddings-reranker-classification-tensorrt/templating/generate_templates.py

they are AUTOGENERATED! please look at generate.py.

add BEI doc

---

mistral/mistral-small-3.1/config.yaml

for real use cases we'll need to raise to TP2 to enable higher sequence length and more images per request, but in-line with gemma 27B, pushing with TP 1 H100.

mistral 3.1 small

---

orpheus-best-performance/model/model.py

Correct `token_gen` handling to grab body_iterator in the case we have that it's an instance of `StreamingResponse`.

fix streaming issue for token gen

---

whisper/faster-whisper-v2/config.yaml
whisper/faster-whisper-v3/config.yaml
whisper/whisper-v3-truss/config.yaml

Move our whisper models to use A10G instead of T4 so that they can get instances much more easily.

Move whispers from T4 to A10G.

---

custom-server/ultravox-0.4/config.yaml

Updated vLLM image version for ultravox 0.4 to support up to fixie-ai/ultravox-v0_5-llama-3_2-1b.
Reference https://docs.vllm.ai/en/v0.8.5/models/supported_models.html
Going from 0.5.5 to 0.8.5

Updated vLLM image version for ultravox 0.4

---

custom-server/ultravox-0.4/config.yaml

Removed HF Access Token (not needed, just causes problems for the customer)
Changed example audio to be a public URL (baseten cdn at this time has a robots.txt)
Added audio support in requirements.

Ultravox 0.4 fixes and audio support

---

custom-server/ultravox-0.4/config.yaml
custom-server/ultravox-0.5-8b/config.yaml
custom-server/ultravox-0.6-70b/config.yaml

Seems this is necessary for better readability and also to have it show up as needing the secret from the model library:
https://basetenlabs.slack.com/archives/C052AKXNGES/p1752263630617429
This change is unintuitive, but when deployed in model library, will prompt users who try to deploy the model with a hf token and also indicate the repo they need to get access to.

Move hf_access_token to a dedicated field in config.yaml

---

orpheus-best-performance/config.yaml
orpheus-best-performance/model/model.py

Due to Orpheus limitations at long contexts, we chunk the prompt as naturally as possible based on natural sentence breaks, into 300 character chunks. Then we pass each chunk as a request to the engine. After 300 characters, it gets risky and Orpheus no longer follows the prompt.

Chunk responses in natural manner
