llama-2-7b-chat/model/model.py

Streaming was broken for the Llama 7b streaming truss, this fixes it.

Fix streaming for llama 7b.

---

.gitignore
CONTRIBUTING.md

Getting us started with a style guide for model library models and example Trusses that we can expand over time to make sure models are consistent and demonstrate best practices.

model library style guide

---

llama-2-13b-chat/config.yaml
llama-2-13b-truss/config.yaml
llama-2-70b-chat/config.yaml
llama-2-70b-truss/config.yaml
llama-2-7b-chat/config.yaml
llama-2-7b-truss/config.yaml

Tested in prod on llama-2-chat 7B

Pin dependency versions for Llama 2 models

---

wizard-vllm/config.yaml
wizard-vllm/model/model.py

This PR adds a quick example on how to use vLLM inside of Truss

Add vLLM example

---

sdxl-lora-swapping/README.md
sdxl-lora-swapping/config.yaml
sdxl-lora-swapping/model/model.py

Adds an example Truss that shows how LoRAs can be hot swapped within `predict`.

Added LoRA Swapping Truss

---

wizard-vllm/model/model.py

This PR fixes a bug that prevents responses from being sent in the wizard vLLM example.

Fix wizard vLLM bug

---

mythalion-13b-gptq/config.yaml

This PR adds support for Mythalion-13B-GPTQ.

Add support for Mythalion-13B-GPTQ

---

mistral-7b-instruct-vllm/README.md
mistral-7b-instruct-vllm/config.yaml
mistral-7b-instruct-vllm/model/model.py

This PR adds support for a vLLM implementation of Mistral 7B instruct.

Add vLLM implementation of Mistral

---

mistral-7b-instruct/config.yaml
mistral-7b-instruct/model/model.py
mistral-7b/config.yaml
mistral-7b/model/model.py

Use `AutoModelForCausalLM` instead of the llama loader

fix mistral load

---

whisperx-truss/README.md
whisperx-truss/config.yaml
whisperx-truss/model/model.py

I'm trying to add this Truss for [whisperx](https://github.com/m-bain/whisperX) but I'm having issues loading the model. In the load function, immediately after the model gets downloaded I receive and error saying: "RuntimeError: Model has been downloaded but the SHA256 checksum does not not match. Please retry loading the mode". I tried changing python package versions, but keep getting the same error. Anyone have an idea on how to fix this?

whisperx-truss

---

llama-7b-exllama-streaming/README.md
llama-7b-exllama-streaming/config.yaml
llama-7b-exllama-streaming/model/model.py
llama-7b-exllama/README.md
llama-7b-exllama/config.yaml
llama-7b-exllama/model/model.py

This PR adds two Trusses that showcase how to use ExLlama V2. One streams while the other is a standard generation model.

Adding ExLlama V2 Examples

---

CONTRIBUTING.md
README.md

Removed broken links, switched to using `truss` CLI instead of baseten

Udpated readme.

---

README.md

or check out https://github.com/basetenlabs/truss-examples/tree/sshanker/add-badge-to-readme for what it looks like

Added badge.

---

jina-embeddings/jina-embeddings-v2-base-en/config.yaml

add description

---

mistral/mistral-7b-instruct-vllm/config.yaml
mistral/mistral-7b-instruct-vllm/model/model.py

- Add support of `ignore_eos` 
- Add support of `stream`
- Add support of customizable prompts format & repo_id

Add support of `ignore_eos` to mistral vllm truss 

---

deepspeed-mii/README.md
deepspeed-mii/config.yaml
deepspeed-mii/model/model.py
llama/llama-2-7b-trt-llm/README.md
llama/llama-2-7b-trt-llm/TRT-LLM-README.md
llama/llama-2-7b-trt-llm/config.yaml
llama/llama-2-7b-trt-llm/model/model.py
mistral/mistral-7b-trt-llm/config.yaml
mistral/mistral-7b-trt-llm/model/model.py

- Mimic vllm api in deepspeed truss
- Mimic vllm api in llama 2 7b trt-llm truss
- Support streaming in trt-llm truss

Use vllm api in deepspeed and trt-llm

---

ci.yaml
mistral/mistral-7b-chat/README.md
mistral/mistral-7b-chat/config.yaml
mistral/mistral-7b-chat/model/model.py

Main difference between this and the instruct model is that the inputs to this are a list of dictionaries of the format:
```
[
{"role": "user", "content": "What is the mistral wind?",
{"role": "assistant", "content": "blah blah blah"...
]
```

Add a mistral chat model.

---

mistral/mistral-7b-chat/model/model.py
zephyr/zephyr-7b-alpha/model/model.py

Fix zephyr & mistral trusses.
These should've been keys

Fix zephyr & mistral trusses

---

llama/llama-2-7b-trt-llm/packages/client.py
llama/llama-2-7b-trt-llm/packages/utils.py
mistral/mistral-7b-instruct-chat-trt-llm/config.yaml
mistral/mistral-7b-instruct-chat-trt-llm/packages/client.py
mistral/mistral-7b-instruct-chat-trt-llm/packages/utils.py
mistral/mistral-7b-trt-llm-build-engine/packages/client.py
mistral/mistral-7b-trt-llm-build-engine/packages/utils.py
templates/generate.yaml
templates/trt-llm/packages/client.py
templates/trt-llm/packages/utils.py

This truss incorporates changes from https://github.com/basetenlabs/truss/pull/759 – namely idempotence on model load and spawning of multiple uvicorn workers

add idempotent load and multiple workers to trt-llm examples

---

bin/test_example.py

I committed this change. Running examples here: https://github.com/basetenlabs/truss-examples/actions/runs/7093448728

Fix approach to retrying deploys.

---

ip_adapter/README.md
ip_adapter/config.yaml
ip_adapter/model/model.py
llava/llava-v1.5-7b/README.md

Adds IP adapter to truss examples.

Add IP Adapter

---

.pre-commit-config.yaml
bin/validate_ci.py
ci.yaml

Also add a pre-commit check so that this doesn't happen in the future.

Fix wrong path in ci.yaml

---

.tool-versions
llama/llama-2-7b-trt-llm/packages/inflight_batcher_llm/postprocessing/1/model.py
mistral/mistral-7b-instruct-chat-trt-llm/packages/inflight_batcher_llm/postprocessing/1/model.py
mistral/mistral-7b-trt-llm-build-engine/packages/inflight_batcher_llm/postprocessing/1/model.py
templates/trt-llm/packages/inflight_batcher_llm/postprocessing/1/model.py

Instead of decoding the whole string everytime, we just diff the string from new tokens and (old token + new tokens). This should be cheap and not grow quadratically.

Optimize streaming token decoding

---

playground-v2-aesthetic/config.yaml

Quick update to get Playground in the model library.

add playground metadata

---

playground-v2-aesthetic/README.md
playground-v2-aesthetic/show.py

Fix issues with playground code sample in readme and add show.py like other image models have

update playground code sample

---

mistral/mistral-7b-trt-llm-build-engine/config.yaml
mistral/mistral-7b-trt-llm-build-engine/model/model.py
templates/generate.yaml

This change add ability to specify TRT-LLM engine configurations using convenient DSL, as well as uses cached built engines from HuggingFace if possible

Better TRT-LLM building on the fly engines

---

stablelm-zephyr-3b-vllm/README.md
stablelm-zephyr-3b-vllm/config.yaml
stablelm-zephyr-3b-vllm/model/model.py

The base image is generated from the root of the vllm Github repo to get the latest support for this StableLM l

Add StableLM Zephyr 3B with vllm async engine

---

.pre-commit-config.yaml
templates/trt-llm/model/model.py
templates/trt-llm/packages/client.py

This PR updates our base TRT-LLM template. Our current Truss is CPU bound, apparent at high loads where CPU hits 100% utilization. The previous fix was to start multiple instances of the Truss server (workers) but this doesn't tackle the root issue. This PR removes the actual bottleneck by leveraging an async GRPC client.
The main changes are:
1. Using async `predict` method instead of threading. 
2. Using an async GRPC client to stream responses
3. Creating one global GRPC stream for all requests 
We benchmark 4 variations of the truss:
- Standard synchronous truss with 1 worker
- Standard synchronous truss with 2 workers 
- Asynchronous truss with 1 worker
- Asynchronous truss with 2 workers
All benchmarks run with `k6`, 240 virtual users within a 60 second duration. The results are …

Optimized TRT-LLM template truss

---

01-getting-started-bert/model/model.py
10-using-system-packages/model/model.py

@squidarth could you please finish the incomplete sentence then run the action to get the docs updated?

docs fixes

---

stable-diffusion/playground-v2-trt/README.md
stable-diffusion/playground-v2-trt/config.yaml
stable-diffusion/playground-v2-trt/model/model.py
stable-diffusion/playground-v2-trt/packages/diffusion/trtclip.py
stable-diffusion/playground-v2-trt/packages/diffusion/trtunet.py
stable-diffusion/playground-v2-trt/show.py

TODO: Remove duplication with the sdxl-trt truss in a follow up.

playground-v2 on trt

---

speculative_decoding/config.yaml
speculative_decoding/model_test.py
speculative_decoding/packages/speculative_decoding.py
speculative_decoding/run_spec_dec.py

* Use Greedy sampling for draft model.
* Add model cache.
* Fix debugging prints.

Speculative Decoding Improvements

---

stable-diffusion/playground-v2-trt/README.md
stable-diffusion/playground-v2-trt/config.yaml

Replace instances of SDXL with Playground v2

Fix Playground readme and config

---

stable-diffusion/stable-diffusion-xl-1.0-trt-h100/README.md
stable-diffusion/stable-diffusion-xl-1.0-trt-h100/config.yaml
stable-diffusion/stable-diffusion-xl-1.0-trt-h100/model/model.py
stable-diffusion/stable-diffusion-xl-1.0-trt-h100/packages/diffusion/trtclip.py
stable-diffusion/stable-diffusion-xl-1.0-trt-h100/packages/diffusion/trtunet.py
stable-diffusion/stable-diffusion-xl-1.0-trt-h100/show.py

todo: Use templates to avoid duplication across various sdxl trt trusses. Let me do that in a follow-up.

sdxl h100 trt truss

---

speculative_decoding/config.yaml
speculative_decoding/engine_building/build_gpt2.py
speculative_decoding/engine_building/build_mistral.py
speculative_decoding/model/model.py
speculative_decoding/model_test.py
speculative_decoding/packages/helpers.py
speculative_decoding/packages/speculative_decoding.py
speculative_decoding/packages/triton_model_repo/draft_model/config.pbtxt
speculative_decoding/packages/triton_model_repo/target_model/config.pbtxt
speculative_decoding/run_spec_dec.py

* Replace baseline mistral with instruction tuned mistral as target model.
* Parameterize the number of draft tokens used and add conventional generation as fallback for no draft tokens (streaming API is supported, only yields full output in one chunk).
* Address some TODOs.
* Fix type annotations.

Speculative Decoding Updates & Fixes

---

stable-diffusion/sdxl-lightning/README.md
stable-diffusion/sdxl-lightning/config.yaml
stable-diffusion/sdxl-lightning/model/model.py

Tested on my account, works amazing!

Add SDXL lightning

---

tensorrt-llm/flan-t5-trt-llm/config.yaml
tensorrt-llm/flan-t5-trt-llm/model/model.py
tensorrt-llm/flan-t5-trt-llm/packages/enc_dec/enc_dec_model.py

* Doesn't support batching
* beam width is fixed at model level in the truss config

flan t5 trt model

---

tensorrt-llm/flan-t5-trt-llm/config.yaml
tensorrt-llm/flan-t5-trt-llm/model/model.py
tensorrt-llm/flan-t5-trt-llm/packages/enc_dec/enc_dec_model.py

* Stop early -- added a stopping criteria for this, couldn't find another way
* Print inference time
* Use hf_access_token from secrets

flat t5 trtllm follow up

---

mistral/mixtral-8x7b-instruct-vllm-a100-t-tp2/README.md
mistral/mixtral-8x7b-instruct-vllm-a100-t-tp2/config.yaml
mistral/mixtral-8x7b-instruct-vllm-a100-t-tp2/model/model.py

Mixtral 8x7B — VLLM TP2 — A100:2

mixtral-8x7b-instruct-vllm-a100-t-tp2

---

llama/llama-3-70b-instruct/README.md
llama/llama-3-70b-instruct/config.yaml
llama/llama-3-70b-instruct/model/model.py

Tuhin's implementation with readme -- tested

Tuhins llama 3 70B with readme

---

nomic/nomic-embed-v1_5/config.yaml
nomic/nomic-embed-v1_5/model/model.py

Fixes Nomic Embed V1.5. Context https://huggingface.co/nomic-ai/nomic-embed-text-v1.5/discussions/19

fix issue with nomic model

---

.github/workflows/warm-chains.yml
chains-examples/docs/audio-transcription/README.md
chains-examples/docs/audio-transcription/data_types.py
chains-examples/docs/audio-transcription/helpers.py
chains-examples/docs/audio-transcription/transcribe.py
chains-examples/docs/audio-transcription/whisper_chainlet.py

Copied the whisper code into this repo for now because this is where I'm running the cronjob, but we should not link to this anywhere & consolidate eventually.

Add whisper chainlet to warmups.

---

flux/README.md
flux/dev/config.yaml
flux/dev/model/model.py
flux/schnell/config.yaml
flux/schnell/model/model.py

added flux schnell and flux dev

added flux model

---

reflection/reflection-llama-3.1-70B/README.md
reflection/reflection-llama-3.1-70B/config.yaml

Reflection Llama 3.1 70B

---

llama/llama-3_1-8b-instruct-sglang/config.yaml
llama/llama-3_1-8b-instruct-sglang/model/model.py
llama/llama-3_1-8b-instruct-trt-llm/config.yaml

Experimental support with SGLang for future benchmarking, such as comparison with vLLM and TensorRT LLM.
ref
https://lmsys.org/blog/2024-07-25-sglang-llama3/
https://lmsys.org/blog/2024-09-04-sglang-v0-3/
Hi @pankajroark @philipkiely-baseten @squidarth @aspctu May you help review this PR? And do you have any suggestions? Thanks.
Llama 3.1 70B and FP8 versions will be completed in separate PRs. The benchmark script will also be completed in a separate PR, similar to https://github.com/sgl-project/sglang/blob/main/python/sglang/bench_serving.py

support Llama 3.1 8B Instruct with SGLang and TensorRT LLM

---

mistral/pixtral-12b/README.md
mistral/pixtral-12b/config.yaml
mistral/pixtral-12b/model/model.py

Title. I have tested this on prod. No support for vllm openai server mode since I want to get this out today, however the non-openai mode has the same api as openai mode.

add pixtral-12b to examples

---

whisper/whisper-v3-turbo/README.md
whisper/whisper-v3-turbo/config.yaml

Tested and works! The TensorRT-LLM Engine Builder is a modern miracle.

whisper turbo engine

---

llama/llama-3_2-11b-vision-instruct/README.md
llama/llama-3_2-11b-vision-instruct/config.yaml
llama/llama-3_2-11b-vision-instruct/model/helper.py
llama/llama-3_2-11b-vision-instruct/model/model.py

Added llama3.2 vision instruct with vllm

Derrick/bt 12247 add llama 3.2 11b

---

nemotron/llama-3-1-nemotron-70b-instruct/README.md
nemotron/llama-3-1-nemotron-70b-instruct/config.yaml

Tested in prod. https://x.com/philip_kiely/status/1846736682915164481

Add Llama-3.1-Nemotron-70B-Instruct

---

llama/engine-llama-3-3-70b-instruct/README.md
llama/engine-llama-3-3-70b-instruct/config.yaml

llama 3.3 engine

---

custom-server/infinity-embedding-server/config.yaml

infinity - Update config.yaml

---

llama/engine-llama-3-1-70b-instruct/config.yaml
llama/engine-llama-3-1-8b-instruct/config.yaml
llama/engine-llama-3-3-70b-instruct/config.yaml

Update most popular llama models with long context engines.
Tested these myself, able to get ~9k tokens from each model.

update llama models for long context

---

deepseek/engine-deepseek-r1-distill-llama-70b/README.md
deepseek/engine-deepseek-r1-distill-llama-70b/config.yaml
deepseek/engine-deepseek-r1-distill-qwen-32b/README.md
deepseek/engine-deepseek-r1-distill-qwen-32b/config.yaml

Add deepseek qwen and llama engines via engine builder.
Manually tested and confirmed working

add deepseek engines

---

deepseek/engine-deepseek-r1-distill-qwen-7b/README.md
deepseek/engine-deepseek-r1-distill-qwen-7b/config.yaml

DeepSeek 7B Distill

---

falcon/falcon3-10B-trt-llm-spec-dec/config.yaml
falcon/falcon3-3B-trt-llm-engine-high-throughput/config.yaml

A couple of small changes for consistency.
Also in the lord of the rings it was eagles, not falcons.

update falcon metadata

---

qwen/engine-qwen-3-06b/config.yaml
qwen/engine-qwen-3-32b/config.yaml
qwen/engine-qwen-3-4b/config.yaml

To pick up the latest b10_lookahead versions.

update b10_lookahead briton-server versions

---

custom-server/ultravox-0.5-8b/README.md
custom-server/ultravox-0.5-8b/config.yaml
custom-server/ultravox-0.6-70b/README.md
custom-server/ultravox-0.6-70b/config.yaml

Capitalize b in the parameters of the model name

---

z-ai/glm-4-5-air-fp8/README.md
z-ai/glm-4-5-air-fp8/config.yaml
z-ai/glm-4-5-fp8/README.md
z-ai/glm-4-5-fp8/config.yaml

Add examples for Air and full GLM 4.5. Will be adding Air to the model library, full is just there as a reference as it has major hardware requirements.

GLM 4.5 examples
